package static

import (
	_ "embed"
	"fmt"
	"strconv"
	"strings"

	"github.com/lilybw/go-solid/internal/meta"
)

// Generating the module
// -----------------------------------------------------------------------------
// The module is a small TypeScript library written into its own directory. It
// is TypeScript rather than JavaScript beside a .d.ts because a .d.ts only
// describes a module the compiler already knows about — it has to be pulled
// into the program by tsconfig before it means anything, and the name it
// declares has to match the name the bundler aliases, with nothing checking
// that they agree. Real source in a real directory needs neither: the editor
// types it by reading it, and there is one artifact instead of two joined by a
// string.
//
// esbuild strips the types on the way through, so nothing is paid for this at
// runtime.
//
//	.go_solid/modules/static/
//	  index.ts      what a component imports
//	  runtime.ts    types and the shared loader — never changes
//	  assets.ts     the graph — the only file an asset edit rewrites
//	  README.md     what to import and what to add to tsconfig

const (
	// MODULE_NAME is the directory the module lives in, under the modules root.
	MODULE_NAME = "static"

	INDEX_FILENAME   = "index.ts"
	RUNTIME_FILENAME = "runtime.ts"
	ASSETS_FILENAME  = "assets.ts"
	README_FILENAME  = "README.md"
)

// MODULE_SPECIFIER is what a component imports. The build resolves it through
// an esbuild alias, and the editor resolves it through the tsconfig fragment;
// neither depends on where the workspace happens to be.
const MODULE_SPECIFIER = MODULE_NAMESPACE + "/" + MODULE_NAME

// MODULE_NAMESPACE is the prefix every generated module answers under. The "@"
// keeps it from colliding with a relative path or a real package name.
const MODULE_NAMESPACE = "@go_solid"

const DISABLED_REASON = "Static assets are disabled. Set Config.Static.Location " +
	"and Config.Static.Mux to enable them."

//go:embed runtime.ts
var runtimeSource string

// GenerateRuntime renders the half of the module that does not depend on what
// is in the asset directory.
func GenerateRuntime() string {
	meta.PanicIfTrue(runtimeSource == "", "[go-solid/internal/static] embed of runtime.ts failed")
	return generatedHeader() + runtimeSource
}

// GenerateAssets renders the asset graph.
func GenerateAssets(m *Manifest) string {
	var b strings.Builder

	b.WriteString(generatedHeader())
	b.WriteString(`import type { AssetURL } from "./runtime";

// Every leaf is the content-hashed URL of one file under the configured static
// directory. Changing a file changes its URL, which is what makes these safe to
// cache forever.
const assets = `)
	writeObject(&b, m.Tree, 0)
	b.WriteString(";\n\nexport default assets;\n")
	return b.String()
}

// GenerateIndex renders the module's public surface.
func GenerateIndex() string {
	return generatedHeader() + `//	import S from "` + MODULE_SPECIFIER + `";
//
//	<img src={S.images.logo} />
//	const config = await S.load(S.data.config);

import assets from "./assets";
import { load, loadJSON, loadText } from "./runtime";

export * from "./runtime";
export { assets };

export default { ...assets, load, loadText, loadJSON };
`
}

// GenerateDisabledAssets renders the graph of a feature that is off.
//
// It has to be a module that resolves and exports something, or a component
// importing the specifier fails at the bundler with an error about a file it
// never wrote — instead of at the compiler, with the reason and the setting.
func GenerateDisabledAssets() string {
	return generatedHeader() + `import type { FeatureDisabled } from "./runtime";

const assets = {} as unknown as FeatureDisabled<` + strconv.Quote(DISABLED_REASON) + `>;

export default assets;
`
}

// GenerateDisabledIndex renders the surface of a feature that is off.
//
// Reaching into the default export is a type error naming the setting, which is
// the one signal a compiler can give that a reader cannot miss. The @deprecated
// tag is there for the editor affordance — strikethrough on the import — and is
// the only tag TypeScript's language service renders. It is not a claim that
// anything is deprecated.
func GenerateDisabledIndex() string {
	return generatedHeader() + `import assets from "./assets";

export * from "./runtime";
export { assets };

/**
 * @deprecated ` + DISABLED_REASON + `
 */
export default assets;
`
}

// GenerateReadme explains how to reach the module. The specifier is not
// guessable and the tsconfig line is not discoverable, so both are written down
// next to the thing they are about.
func GenerateReadme(tsconfigFragment meta.AbsoluteFilePath, enabled bool) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# %s\n\nGenerated by go-solid. Do not edit — every file here is rewritten\n", MODULE_SPECIFIER)
	b.WriteString("whenever the asset directory changes.\n\n## Importing\n\n```ts\nimport S from ")
	fmt.Fprintf(&b, "%s;\n\n", strconv.Quote(MODULE_SPECIFIER))
	b.WriteString("<img src={S.images.logo} />\nconst config = await S.load(S.data.config);\n```\n\n")

	b.WriteString("## Making the editor resolve it\n\n")
	b.WriteString("The build resolves this specifier on its own. Your editor needs to be\n")
	b.WriteString("told once, by extending the fragment go-solid generates:\n\n")
	b.WriteString("```json\n{\n  \"extends\": [")
	fmt.Fprintf(&b, "%s]\n}\n```\n\n", strconv.Quote(relativeFragmentHint(tsconfigFragment)))
	b.WriteString("The fragment maps `" + MODULE_NAMESPACE + "/*` at every generated module,\n")
	b.WriteString("so it stays correct as more of them appear. TypeScript 5.0 and later\n")
	b.WriteString("accept an array here, which composes with an `extends` you already have.\n\n")

	if !enabled {
		b.WriteString("## This feature is off\n\n")
		b.WriteString(DISABLED_REASON + "\n\n")
		b.WriteString("The module still exists so that an import of it resolves; reaching into\n")
		b.WriteString("it is a type error carrying the same sentence.\n")
	}
	return b.String()
}

func generatedHeader() string {
	return "// Code generated by go-solid. DO NOT EDIT.\n//\n"
}

// relativeFragmentHint keeps the README readable on the machine it was written
// on without pretending to know where the reader's tsconfig lives.
func relativeFragmentHint(fragment meta.AbsoluteFilePath) string {
	slashed := strings.ReplaceAll(fragment, "\\", "/")
	if index := strings.LastIndex(slashed, "/.go_solid/"); index >= 0 {
		return "." + slashed[index:]
	}
	return slashed
}

// writeObject renders one directory as a nested object literal.
func writeObject(b *strings.Builder, dir *Dir, depth int) {
	pad := strings.Repeat("  ", depth+1)
	closing := strings.Repeat("  ", depth)

	b.WriteString("{\n")
	for _, child := range dir.Dirs {
		fmt.Fprintf(b, "%s%s: ", pad, child.Name)
		writeObject(b, child, depth+1)
		b.WriteString(",\n")
	}
	for _, file := range dir.Files {
		if file.Asset != nil {
			writeLeaf(b, pad, file.Key, file.Asset)
			continue
		}
		fmt.Fprintf(b, "%s%s: {\n", pad, file.Key)
		for _, variant := range file.ByExtension {
			writeLeaf(b, pad+"  ", variant.Key, variant.Asset)
		}
		fmt.Fprintf(b, "%s},\n", pad)
	}
	b.WriteString(closing)
	b.WriteString("}")
}

// writeLeaf renders one asset: its URL, asserted to the branded type so the
// media type travels with it, and its path on disk as a comment so the key can
// be traced back to the file it came from.
func writeLeaf(b *strings.Builder, pad, key string, asset *Asset) {
	fmt.Fprintf(b, "%s/** %s */\n", pad, asset.Rel)
	fmt.Fprintf(b, "%s%s: %s as AssetURL<%s>,\n",
		pad, key, strconv.Quote(asset.URL), strconv.Quote(asset.MIME))
}
