package static

import (
	"fmt"
	"strconv"
	"strings"

	_ "embed"
)

// Generating the module and its definitions
const MODULE_FILENAME = "static.js"

// MODULE_SPECIFIER is what a component imports. esbuild resolves it to the
// generated file through an alias, so the path never appears in user code.
const MODULE_SPECIFIER = "go-solid/static"
const DEFINITION_FILENAME = "static.d.ts"
const DISABLED_REASON = "Static assets are disabled. Set Config.Static.Location " +
	"and Config.Static.Mux to enable them."

// GenerateModule renders the JavaScript a component imports.
func GenerateModule(m *Manifest) string {
	var b strings.Builder
	b.WriteString("// Code generated by go-solid. DO NOT EDIT.\n")
	b.WriteString("//\n// Every leaf is the content-hashed URL of one file under the configured\n")
	b.WriteString("// static directory. Changing a file changes its URL, which is what makes\n")
	b.WriteString("// these safe to cache forever.\n\n")

	b.WriteString(loaderSource)
	b.WriteString("\nconst assets = ")
	writeObject(&b, m.Tree, 0)
	b.WriteString(";\n\nexport default { ...assets, load, loadText, loadJSON };\n")
	b.WriteString("export { load, loadText, loadJSON };\n")
	return b.String()
}

func GenerateDisabledModule() string {
	return "// Code generated by go-solid. DO NOT EDIT.\n" +
		"//\n// " + DISABLED_REASON + "\n\n" +
		"export default {};\n"
}

// writeObject renders one directory as a nested object literal.
func writeObject(b *strings.Builder, dir *Dir, depth int) {
	pad := strings.Repeat("  ", depth+1)
	closing := strings.Repeat("  ", depth)

	b.WriteString("{\n")
	for _, child := range dir.Dirs {
		fmt.Fprintf(b, "%s%s: ", pad, child.Name)
		writeObject(b, child, depth+1)
		b.WriteString(",\n")
	}
	for _, file := range dir.Files {
		if file.Asset != nil {
			fmt.Fprintf(b, "%s%s: %s,\n", pad, file.Key, strconv.Quote(file.Asset.URL))
			continue
		}
		fmt.Fprintf(b, "%s%s: {\n", pad, file.Key)
		for _, variant := range file.ByExtension {
			fmt.Fprintf(b, "%s  %s: %s,\n", pad, variant.Key, strconv.Quote(variant.Asset.URL))
		}
		fmt.Fprintf(b, "%s},\n", pad)
	}
	b.WriteString(closing)
	b.WriteString("}")
}

//go:embed loader.js
var loaderSource string

// GenerateDefinition renders the TypeScript describing the module.
func GenerateDefinition(m *Manifest) string {
	var b strings.Builder
	b.WriteString(definitionPreamble)
	fmt.Fprintf(&b, "declare module %s {\n", strconv.Quote(MODULE_SPECIFIER))
	b.WriteString(loaderDeclarations)
	b.WriteString("\n  const assets: ")
	writeType(&b, m.Tree, 1)
	b.WriteString(";\n\n  export default assets;\n}\n")
	return b.String()
}

//go:embed types.ts
var definitionPreamble string

func GenerateDisabledDefinition() string {
	return definitionPreamble +
		"declare module " + strconv.Quote(MODULE_SPECIFIER) + " {\n" +
		"  /**\n" +
		"   * @deprecated " + DISABLED_REASON + "\n" + // for editor highlighting
		"   */\n" +
		"  const assets: FeatureDisabled<" + strconv.Quote(DISABLED_REASON) + ">;\n" +
		"  export default assets;\n}\n"
}

const loaderDeclarations = ` /** Fetch an asset, decoded by the media type the server reports. */
  export function load<M extends string>(url: AssetURL<M>, init?: RequestInit): Promise<DataFor<M>>;
  /** Fetch any URL as a Blob. The escape hatch for hand-written paths. */
  export function load(url: string, init?: RequestInit): Promise<Blob>;
  /** Fetch an asset as text, whatever its media type. */
  export function loadText(url: string, init?: RequestInit): Promise<string>;
  /** Fetch an asset as parsed JSON, whatever its media type. */
  export function loadJSON(url: string, init?: RequestInit): Promise<unknown>;
`

// writeType renders one directory as a nested object type.
func writeType(b *strings.Builder, dir *Dir, depth int) {
	pad := strings.Repeat("  ", depth+1)
	closing := strings.Repeat("  ", depth)

	b.WriteString("{\n")
	for _, child := range dir.Dirs {
		fmt.Fprintf(b, "%s%s: ", pad, child.Name)
		writeType(b, child, depth+1)
		b.WriteString(";\n")
	}
	for _, file := range dir.Files {
		if file.Asset != nil {
			fmt.Fprintf(b, "%s/** %s */\n", pad, file.Asset.Rel)
			fmt.Fprintf(b, "%s%s: AssetURL<%s>;\n", pad, file.Key, strconv.Quote(file.Asset.MIME))
			continue
		}
		fmt.Fprintf(b, "%s%s: {\n", pad, file.Key)
		for _, variant := range file.ByExtension {
			fmt.Fprintf(b, "%s  /** %s */\n", pad, variant.Asset.Rel)
			fmt.Fprintf(b, "%s  %s: AssetURL<%s>;\n", pad, variant.Key, strconv.Quote(variant.Asset.MIME))
		}
		fmt.Fprintf(b, "%s};\n", pad)
	}
	b.WriteString(closing)
	b.WriteString("}")
}
