package static

import (
	"fmt"
	"path/filepath"

	io_int "github.com/lilybw/go-solid/internal/io"
	"github.com/lilybw/go-solid/shared/meta"
)

// Making the editor resolve a generated module
// -----------------------------------------------------------------------------
// The build resolves the specifier through an esbuild alias, which go_solid
// controls. The editor resolves it through the consumer's tsconfig, which
// go_solid does not — and cannot, because the workspace may be anywhere and the
// tsconfig is theirs.
//
// So the mapping is written out as a fragment they extend once. It is a single
// wildcard rather than an entry per module, which means it stays correct as
// more modules appear and they never touch it again.
//
// The division is deliberate: the alias is build correctness and is ours, the
// fragment is editor experience and is theirs. A consumer who never adds it
// loses autocomplete, not the build.

// TSCONFIG_FRAGMENT_NAME is the file consumers extend.
const TSCONFIG_FRAGMENT_NAME = "tsconfig.paths.json"

// TSConfigFragmentPath is where the fragment is written.
func TSConfigFragmentPath(workspace meta.AbsoluteDirectoryPath) meta.AbsoluteFilePath {
	return filepath.Join(workspace, TSCONFIG_FRAGMENT_NAME)
}

// tsconfigFragment maps the namespace at the modules directory.
//
// There is no baseUrl: since TypeScript 4.1 a paths entry without one resolves
// relative to the config file holding it, which is exactly what is wanted here
// and avoids changing how the consumer's own non-relative imports resolve.
const tsconfigFragment = `{
  "//": "Generated by go-solid. Extend this from your tsconfig.json to import generated modules by name.",
  "compilerOptions": {
    "paths": {
      "` + MODULE_NAMESPACE + `/*": ["./` + MODULES_DIR_NAME + `/*"]
    }
  }
}
`

// EnsureTSConfigFragment writes the fragment, and reports whether it changed.
func EnsureTSConfigFragment(workspace meta.AbsoluteDirectoryPath) (meta.AbsoluteFilePath, error) {
	path := TSConfigFragmentPath(workspace)
	if err := io_int.WriteAtomicMode(path, []byte(tsconfigFragment), 0o644); err != nil {
		return "", fmt.Errorf("go_solid/static: write %q: %w", path, err)
	}
	return path, nil
}
