// Code generated by go-solid/internal/static. DO NOT EDIT.

declare const MIME: unique symbol;

/**
 * The content-hashed URL of one static asset, carrying its media type.
 *
 * It is a string, so it drops into anything expecting one:
 *
 *     <img src={S.images.logo} />
 *
 * The brand is phantom — it exists only here, never at runtime — and is what
 * lets load() know what it will hand back.
 */
type AssetURL<M extends string = string> = string & { readonly [MIME]: M };

/** What load() resolves to, per media type. Anything unlisted gives a Blob. */
interface AssetData {
  "application/json": unknown;
  "application/manifest+json": unknown;
  "image/svg+xml": string;
  "text/css": string;
  "text/csv": string;
  "text/html": string;
  "text/plain": string;
}

type DataFor<M extends string> = M extends keyof AssetData ? AssetData[M] : Blob;

/**
 * A feature that was never switched on. Reaching into one is a type error
 * carrying the reason.
 */
type FeatureDisabled<Reason extends string> = {
  readonly __GO_SOLID_DISABLED__: Reason;
};