services:
  unix:
    build:
      context: ..
      dockerfile: ./testing_environment/Dockerfile.Unix
    image: go-solid-test:unix
    container_name: go-solid-unix
    volumes:
      - ./logs-unix:/logs

  windows:
    build:
      context: ..
      dockerfile: ./testing_environment/Dockerfile.Windows
    image: go-solid-test:windows
    container_name: go-solid-windows
    volumes:
      - ./logs-windows:/logs